package android.example.uptoskills

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.ImageView
import android.widget.TextView

class PrivacyPolicyActivity : AppCompatActivity() {


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_privacy_policy)

        findViewById<TextView>(R.id.policy).text = "UptoSkills respects and understands the importance of your privacy – and are therefore committed to affording complete protection to the personal information of our customers who use our products and services or visitors of our website, and of the learners whose information we may have access to and when you apply on our website for an open position. It is in recognition of this need for security, our commitment and Secured management of any information received /collected by us that UptoSkills has established this Privacy Policy.This privacy policy is applicable to our websites – https://www.Uptoskills.com and and to our products, including the UptoSkills and shop platform, and any services we provide. It also applies to our marketing practices. We ensure total transparency in all our dealings.\n" +
                "\n" +
                "WHAT INFORMATION IS COLLECTED?\n" +
                "1. Personal information collected on our website\n" +
                "As a general practice, no personal Information is collected about a visitor to the website, apart from the personal information submitted by the visitor himself/herself in a ‘contact us’ form or ‘submit resume’ link. We shall use such Personal Information for the purpose you share it with us. However, at times, certain information may be collected from you when you visit the website. Such information is aggregated to measure the number of visits, average time spent on the website, pages viewed etc. This gives us an idea of which parts of our website users are visiting, in order that we may improve the content to offer you better services. We do not link IP addresses to anything personally identifiable. This means that a user’s session will be tracked, but the user will be anonymous.\n" +
                "\n" +
                "2. ID, Customer information for support and maintenance\n" +
                "When you register to use a UptoSkills product, create an ID with us or use our services for development or support we collect information that is unique to you and identifies you. This may include your name, email address, phone number or payment information all in accordance with applicable law. Some information is required and other information is optional. Sometimes information regarding eligibility may be required. At times we may rely on information from public sources.\n" +
                "\n" +
                "3. Information collected while using our online products and applications especially during activation and automatic updates\n" +
                "When our product/application is used information may be collected on how it is used. We may collect information (like an IP address, or the type of device used) that your browser or device typically sends to our servers whenever you use our website, product or application. We may use information that led you to our website – for example the search terms used or the device being used - through cookies and similar technologies. Often this information is anonymous and if associated with you kept strictly confidential. If you do not want us to collect this information, you can tell us by opting out or by either declining or customising cookie settings on our website\n" +
                "\n" +
                "4. UptoSkills emails\n" +
                "We do contact organisation or executives as a part of our marketing campaigns. We do so, as we believe we have legitimate interest to promote our products and services and it also benefits our prospects. We do not do any mass mailing and carefully reach out to selected professional with a personalised approach. The emails we send you as part of our marketing campaigns allow us to know if you have received or opened the email, or clicked a link within the email. If you do not want us to collect this information from marketing emails, you can opt out of receiving such emails by clicking on the unsubscribe button.\n" +
                "\n" +
                "5. Buttons or tools on our websites related to other companies and social media pages\n" +
                "Our websites may include buttons or tools that link to other companies’ services (for example, a Facebook or Google button). We may collect information about your use of these features. In addition, when you see or interact with these buttons, tools, or content, or view a UptoSkills web page containing them, some information from your browser may automatically be sent to the other company. Please read that company’s privacy policy for more information, as these sites may have their own privacy statements in place, which we recommend you review if you visit any linked Web sites. We are not responsible for the content of linked sites or any use of the sites or for the privacy practices of those other Web sites.We may collect information when you interact with our social networking pages or use the sign-on features.\n" +
                "\n" +
                "6. Hosted services provided by UptoSkills\n" +
                "We provide hosted services to many companies that may sometimes require the collection of information through cookies and other technology to collect analytic data required by the product and to understand our users and their likely interests. No information is collected without consent. Management of technified private limited operates the website www.uptoskills.com.\n" +
                "\n" +
                "WHERE DO WE STORE THIS DATA?\n" +
                "Information and data files are stored on our servers and the servers of companies we hire to provide services to us. We do not share, sell or lease any kind of information collected to any third parties for their marketing uses.\n" +
                "\n" +
                "HOW DO WE USE THE INFORMATION COLLECTED?\n" +
                "Information Collected from Interactive Forms On some of our web pages we offer interactive forms that let you voluntarily submit personal information (such as your e-mail address, name, or organization). This occurs when you are registering for ODL counseling; various tests, quizzes, seminars, workshops, or training sessions offered by Teach Tech Services, downloading admission forms from Teach Tech Services. In those cases, all submitted information is used only for the purposes for which it is intended and is not made available to any third party.\n" +
                "\n" +
                "We use this information to:\n" +
                "To fulfil our contractual commitment and to enhance the performance of our contract with you.Allow you use of our products and applications and respond to your requests Provide you with the services, support or information requested and monitor effectiveness Improve our website’s user experience and communicate better to engage users Enhance the effectiveness of our marketing campaigns. To send marketing emails or messages related to our products and services Monitor aggregate metrics to conduct our market research and understand our customers better To process your job application for an open position. Analyze, diagnose and fix issues in our product and service offerings. In all cases this information is not shared with any third party. It is used by UptoSkills as above or to prevent/respond to protection of our websites or applications. In some cases like with hosted services, we may share information with those that provide us with technology services (e.g. web hosting and analytics services), but strictly for the purpose of carrying out our work. All such vendors used by us have signed a Data protection agreement with UptoSkills to secure your data. We may be required to share information with law enforcement or other third parties when compelled to do so by court order or other legal process, to comply with statutes or regulations.\n" +
                "\n" +
                "If we merge with or are acquired by another company, and if all of our assets are acquired by another company, this information will most likely be one of the assets to be transferred. However, we will not transfer any personal information of our customers until absolutely necessary to provide you with a continuity of service and only when the new owner maintains and provides the same level of data privacy standards as we do. In such cases, we will provide you with notice and an opportunity to opt-out of the transfer of identifiable data.\n" +
                "\n" +
                "HOW DO WE SECURE INFORMATION COLLECTED?\n" +
                "We understand that the security of your information is vital and have in place strong administrative, technical, and physical security controls and measures to keep data safe and secure. Our privacy practices are designed to provide protection for your personal information, all over the world. To protect information stored in our servers, through Amazon Web Service infrastructure at various locations like the US, Australia and India, access is limited (through user/password credentials and two factor authentication) to those employees who require it to perform their job functions. We use industry-standard Secure Socket Layer (SSL) encryption technology to safeguard the account registration process and sign-up information. Other security safeguards include but are not limited to multifactor authentication, data encryption, firewalls, and physical access controls to building and files. We would like to caution our visitors about phishing attacks, wherein unscrupulous third parties seek to extract sensitive and confidential information from you by posing as a genuine website or by sending an email misrepresenting it to be from a genuine source. Please be aware that we never seek sensitive or confidential information such as regarding your financial or health record through emails or through our websites. If you receive such a message claiming to be from UptoSkills , then please do not reply to it and immediately bring it to our attention by contacting the Webmaster. UptoSkills , also recognizes the receipt, transmission or distribution of spam emails (unsolicited bulk emails) as a major concern and has taken reasonable measures, to minimize the transmission and effect of spam emails in its computing environment.\n" +
                "\n" +
                "CAN THIS INFORMATION BE REVIEWED?\n" +
                "In some cases and at our discretion this information may be accessed by respective organizations to correct any mistake in that information, and to delete any information we no longer have business reasons for retaining. You can do this by sending us an email. UptoSkills , strives to comply with all applicable laws around the globe that are designed to protect your privacy and information, no matter where that information is collected, transferred, or retained. Although legal requirements may vary from country to country, we intend to adhere to the principles set forth in this Privacy Policy even if information is transferred from your country to other countries that may not require an adequate level of protection for your information.\n" +
                "\n" +
                "RIGHTS OVER YOUR PERSONAL DATA\n" +
                "Under certain circumstances, by law you have the right to: Be informed about the processing of your personal data (i.e. for what purposes, what types, to what recipients it is disclosed, storage periods, any third party sources from which it was obtained, confirmation of whether we undertake automated decision-making, including profiling, and the logic, significance and envisaged consequences). Object to your personal data being processed for a particular purpose or to request that we stop using your information. Request not to be subject to a decision based on automated processing and to have safeguards put in place if you are being profiled based on your personal data.\n" +
                "\n" +
                "Ask us to transfer a copy of your personal data to you or to another service provider or third party where technically feasible and otherwise required by applicable regulations. Withdraw, at any time, any consent that you have previously given to us for our use of your personal data. Ask us to stop or start sending you marketing messages at any time. Request access to your personal data (commonly known as a \"data subject access request\"). This enables you to receive a copy of the personal data we hold about you and to check that we are lawfully processing it. Request correction of the personal data that we hold about you. This enables you to have any incomplete or inaccurate information we hold about you corrected. It is important that the personal data we hold about you is accurate and current. Please keep us informed if your personal data changes during your working relationship with us. Request the erasure of your personal data. This enables you to ask us to delete or remove personal data where you think that we do not have the right to process it.\n" +
                "\n" +
                "Any request for access to or a copy of your personal data must be in writing and we will endeavour to respond within a reasonable period and in any event within one month in compliance with Data Protection Legislation. We will provide this information free of charge unless the request is manifestly unfounded or excessive. We will comply with our legal obligations as regards any individual’s rights as a data subject. If you would like to contact us in relation to any of the rights set out above please contact us by email info@UptoSkills.com and/or at F-765/188, raj nagar II, palam colony, New Delhi, 110077. To protect your privacy and security, we may take reasonable steps to verify your identity before providing you with the details. RIGHT TO COMPLAIN You can contact the ICO if you have any concerns about how UptoSkills has handled your personal data and you also have the right to make a complaint at any time to the Information Commissioner's Office (ICO), the supervisory authority for data protection issues. You can contact the ICO to find out more information about your rights as a data subjects, their regulatory powers and actions they can take on their website.\n" +
                "\n" +
                "REASONABLE SECURITY PRACTICES AS PER INFORMATION TECHNOLOGY ACT, 2000 AND ITS RULES\n" +
                "We have implemented reasonable security practices as per Rule 8 of the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 of Information Technology Act, 2000 amended through Information Technology Amendment Act, 2008. Access to your personal account online is password protected. We will not release your account password to any person. In the event that you forget your password, you may generate an on-line request for your password to be sent to you by e-mail at the e-mail address used during registration.\n" +
                "\n" +
                "We have implemented stringent, internationally acceptable standards of technology, managerial security, technical security, operational security and physical security in order to protect personally identifiable information from loss, misuse, disclosure, alteration or destruction. The data resides behind a firewall, with access restricted to our authorized personnel. We have implemented “Reasonable Security Practices” as required by the Information Technology Act, 2000 rules including any amendment in the said Act and its rules. By complying with such provisions, we assure you proper care and control over our Information Technology and Security operations under sections 43, 43A, 45, 66,72A & 85 of I.T. Act, 2000 and I.T.A.A, 2008 including related rules and therefore you agree that we shall not be held responsible for any activity in your account which results from your failure to keep your own password/mobile secured.\n" +
                "\n" +
                "By using this service you agree that we shall not be held responsible for any uncontrollable security attacks and in such cases you agree that we shall not be held responsible for any type of financial losses, loss of opportunity, legal cost, business losses, reputation loss, direct and indirect losses that may occur to you as per the Provisions of Section 43, 43A and 45 of Information Technology Act, 2000 including any amendments in the said Act and any other laws of India for the time being in force. You further agree that our management shall not be held responsible directly or indirectly for any cybercrime related criminal liabilities under I.T. Act, 2000 relating to your information as you have agreed and acknowledged that our management complies with due diligence (care & controls) requirements of I.T. Act, 2000 including its rules and amendments.\n" +
                "\n" +
                "GoDaddy provides complete list of information security controls of server on which our service is hosted. Further, you also agree and acknowledge that our management shall never be held responsible regarding privacy of your sensitive personal data in case of sharing your sensitive personal data to any authorized cyber investigation agency of appropriate government authorities under sections 67C, 69, 69A, 69B, 70B, 79 and 80 of I.T.Act,2000 including its amendments and rules.\n" +
                "\n" +
                "NOTIFICATION OF CHANGES\n" +
                "If we decide to change our privacy policy, we will post those changes on this page so our users are always aware of the information we collect and how we use it. If at any point we decide to use personally identifiable information in a manner different from that stated at the time it was collected, we will notify users by way of an email. Users will have a choice as to whether or not we use their information in this different manner. We will use information in accordance with the privacy policy under which the information was collected. Where links are provided to other websites it should be noted that they are not and cannot be governed by our Privacy Statement. We cannot guarantee your privacy when you access other websites through any link provided on this website.\n" +
                "\n" +
                "UptoSkills Logo\n" +
                "UptoSkills is committed to humanity’s pursuit of happiness by making lifelong digital learning accessible, affordable, and sustainable. info@UptoSkills.com Privacy Policy Effective date: April 1, 2021\n" +
                "    \n" +
                "Copyright © 2021 UPTOSKILLS . All Rights Reserved.   Return and Refund Policy     Privacy Policy     Terms of use     Site Map      Powered By: Socialupstairs\n"

        findViewById<ImageView>(R.id.back).setOnClickListener {
            finish()
        }
    }

    override fun onBackPressed() {
        if(parent == null) {
            val intent = Intent(this, MainActivity::class.java)
            startActivity(intent)
            finish()
        }
        super.onBackPressed()
    }
}